/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaLogin;

/**
 *
 * @author luqui
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TelaCadastro");
        getContentPane().setLayout(null);

        jLabel1.setText("Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 101, 28, 14);
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(70, 56, 242, 20);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 59, 31, 14);

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(70, 95, 242, 20);

        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 136, 34, 14);

        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField3);
        jFormattedTextField3.setBounds(70, 133, 244, 20);

        jButton1.setText("Voltar");
        getContentPane().add(jButton1);
        jButton1.setBounds(711, 382, 61, 23);

        jLabel4.setText("Telefone:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 174, 46, 14);
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(72, 171, 242, 20);

        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 202, 23, 14);
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(72, 199, 242, 20);

        jLabel6.setText("RG:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 255, 18, 14);
        getContentPane().add(jFormattedTextField6);
        jFormattedTextField6.setBounds(72, 259, 242, 20);

        jLabel7.setText("Rua:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(479, 59, 23, 14);

        jLabel8.setText("Bairro:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(475, 136, 32, 14);

        jLabel9.setText("Cidade:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 174, 37, 14);

        jLabel10.setText("CEP:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(484, 262, 23, 14);

        jLabel11.setText("Estado:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 213, 37, 14);

        jLabel12.setText("Número:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(466, 98, 41, 14);
        getContentPane().add(jFormattedTextField13);
        jFormattedTextField13.setBounds(530, 56, 242, 20);
        getContentPane().add(jFormattedTextField14);
        jFormattedTextField14.setBounds(530, 95, 242, 20);
        getContentPane().add(jFormattedTextField15);
        jFormattedTextField15.setBounds(530, 133, 242, 20);
        getContentPane().add(jFormattedTextField16);
        jFormattedTextField16.setBounds(530, 171, 242, 20);
        getContentPane().add(jFormattedTextField17);
        jFormattedTextField17.setBounds(530, 210, 242, 20);
        getContentPane().add(jFormattedTextField18);
        jFormattedTextField18.setBounds(530, 259, 242, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel13.setText("Cadastre - se");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(244, 11, 258, 34);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(24, 0, 0, 0);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Tela de cadastro_1.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 860, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
